version: "2"

services:
  api:
    build: .
    container_name: nando_api
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=/app/server.py
    command: 'python -m flask run --host=0.0.0.0'